language: node_js
node_js:
    - 6
	- 8
	- 10
cache:
    directories:
        - node_modules
script: npm test
deploy:
    provider: pages
    local-dir: dist
    skip-cleanup: true
    github-token: $GITHUB_PAGES_DEPLOY_TOKEN
    keep-history: true
    target-branch: gh-pages
    fqdn: gitmoji.js.org
    on:
        branch: i18n/cn

# blocklist
branches:
    only:
        - i18n/cn
